import { execSync } from "node:child_process";
import { join } from "node:path";
import { writeFile } from "../utils/fs.js";
import type { PipelineContext } from "../commands/create.js";

export function initRepo(ctx: PipelineContext): void {
  const { domainSpec, outputDir } = ctx;
  const d = domainSpec.domain;

  // README.md
  const readme = `# CampForge: ${d.name}

Agent camp for ${d.name}.

## Install

\`\`\`bash
./campforge-cli.sh
\`\`\`

## Skills

${d.curriculum.core.map((s) => `- **${s.skill_id}**: ${s.spec?.description || s.skill_id}`).join("\n")}

## Validate

\`\`\`bash
campforge validate .
\`\`\`

---

Generated by [CampForge](https://github.com/planetarium/CampForge)
`;

  writeFile(join(outputDir, "README.md"), readme);

  // Git init (best-effort)
  try {
    execSync("git init", { cwd: outputDir, stdio: "ignore" });
  } catch {
    // git not available, skip
  }
}
